s3_service:
    protocol: 'https'
    name: 's3.pl-waw.scw.cloud'
    bucket_name: 'dinvisel-media'
    region_name: 'pl-waw'

assets:
  din_laughing: 'vin_laugh.jpg'

application:
  hosted_address: 'https://dinvisel.herokuapp.com/'
  port: '8443'